apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: interrogation-service
  name: interrogation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: interrogation-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker/docker-compose.yaml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: interrogation-service
    spec:
      containers:
        - command:
            - /app/wait-for-it.sh
            - db:5432
            - --
            - /app/interrogationservice
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/oda
          image: ghcr.io/vfiftyfive/oda-interrogationservice:latest
          name: interrogation-service
          ports:
            - containerPort: 50054
              protocol: TCP
      restartPolicy: Always
